export const PASSWORD_RESET_LINK_REQUEST = "PASSWORD_RESET_LINK_REQUEST";
export const PASSWORD_RESET_LINK_SUCCESS = "PASSWORD_RESET_LINK_SUCCESS";
export const PASSWORD_RESET_LINK_FAIL = "PASSWORD_RESET_LINK_FAIL";
export const PASSWORD_RESET_LINK_RESET = "PASSWORD_RESET_LINK_RESET";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_RESET = "RESET_PASSWORD_RESET";


//profile
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
